GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2F1cmF2IiwiaWF0IjoxNjMzMTcwMDk3LCJleHAiOjE2MzMxNzAxMTJ9.keyv8OhxJda6ZAjmBCeK5_oOwnWfkb_0NtHogTB8bDQ

###

POST http://localhost:3001/login
Content-Type: application/json

{
   "username": "Gaurav"
}